# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ntest-as

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ntestacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ea9293dd95a8426d835c9cb9a34f53d4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0b060a3e75ec480abcc1e555013f117e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ntestacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ea9293dd95a8426d835c9cb9a34f53d4 }}/ntest-acr-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ntest-as'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6a7816e89e814930aa15ad37f49dd03f }}
        images: 'ntestacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ea9293dd95a8426d835c9cb9a34f53d4 }}/ntest-acr-image:${{ github.sha }}'