# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - stg-ntest-2-wapp(Production), Build and deploy container app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - uses: azure/docker-login@v1
      with:
        login-server: stgcdrxacr1.azurecr.io/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_79F0584A5E0F48C3A76D42CDE72A2C0C }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_14EB9EDBDD8F41F8AD0B53F790C6AED9 }}

    - run: |
        docker build . -t stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_79F0584A5E0F48C3A76D42CDE72A2C0C }}/stg-ntest-2-wapp-img:${{ github.sha }}
        docker push stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_79F0584A5E0F48C3A76D42CDE72A2C0C }}/stg-ntest-2-wapp-img:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: stg-ntest-2-wapp
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4AFF9D0FB7A745518DA83916F74AF881 }}
        images: stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_79F0584A5E0F48C3A76D42CDE72A2C0C }}/stg-ntest-2-wapp-img:${{ github.sha }}

