# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - stg-ntest-1-wapp(Production), Build and deploy container app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - uses: azure/docker-login@v1
      with:
        login-server: stgcdrxacr1.azurecr.io/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0C5A98FE5FA24DDEA9522139AB6176B4 }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_B453777246544A16B55C7F284799FC2C }}

    - run: |
        docker build . -t stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0C5A98FE5FA24DDEA9522139AB6176B4 }}/stg-ntest-1-wapp-image:${{ github.sha }}
        docker push stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0C5A98FE5FA24DDEA9522139AB6176B4 }}/stg-ntest-1-wapp-image:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: stg-ntest-1-wapp
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E52C471A18A94D7C845614322217612A }}
        images: stgcdrxacr1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0C5A98FE5FA24DDEA9522139AB6176B4 }}/stg-ntest-1-wapp-image:${{ github.sha }}

